"""
M8: Hypothesis Engine Adapter for ML-Assisted Parameter Estimation.

Integrates estimated symbol rate, SNR, and parameter uncertainties into
candidate hypotheses generated by backend/hypothesis/generator.py.
Preserves existing hypothesis scoring mathematics untouched.
"""
from typing import List, Dict, Optional, Any
import numpy as np

from backend.hypothesis.generator import generate_hypotheses_from_ml
from backend.hypothesis.candidates import HypothesisCandidate, EvidenceComponent, EvidenceStatus
from backend.hypothesis.evaluator import create_symbol_rate_evidence, create_snr_evidence
from ml.parameters.inference import ParameterAnalysisResult


def generate_hypotheses_with_parameters(
    ml_probabilities: Dict[str, float],
    parameter_result: ParameterAnalysisResult,
    supported_classes: Optional[List[str]] = None,
    fec_candidates: Optional[List[str]] = None,
    top_k: int = 5,
) -> List[HypothesisCandidate]:
    """
    Generates hypothesis candidates enriched with M8 estimated symbol rate and SNR evidence.
    
    Args:
        ml_probabilities: Dictionary of modulation probabilities from M5/M6 classifier.
        parameter_result: ParameterAnalysisResult from estimate_parameters(...).
        supported_classes: List of supported modulation names.
        fec_candidates: FEC schemes to test.
        top_k: Top predictions to retain.
        
    Returns:
        List of HypothesisCandidate instances ready for evaluation.
    """
    est_baud = parameter_result.symbol_rate.estimate
    est_snr = parameter_result.snr_db.estimate

    # Generate standard candidate hypotheses using existing backend logic
    candidates = generate_hypotheses_from_ml(
        ml_probabilities=ml_probabilities,
        symbol_rate=est_baud,
        supported_classes=supported_classes,
        fec_candidates=fec_candidates,
        top_k=top_k,
    )

    # Attach parameter metadata and evidence traces without altering hypothesis scoring formula
    for cand in candidates:
        cand.sync_assumptions = {
            "estimated_symbol_rate_baud": float(est_baud),
            "symbol_rate_confidence": float(parameter_result.symbol_rate.confidence),
            "symbol_rate_uncertainty": float(parameter_result.symbol_rate.uncertainty),
            "symbol_rate_method": parameter_result.symbol_rate.method,
            "estimated_snr_db": float(est_snr),
            "snr_confidence": float(parameter_result.snr_db.confidence),
            "snr_uncertainty": float(parameter_result.snr_db.uncertainty),
            "sample_rate_hz": float(parameter_result.sample_rate),
        }

        # Real symbol-rate parameter agreement evidence from M8
        cand.evidence.symbol_rate = create_symbol_rate_evidence(
            candidate_baud=cand.symbolRate,
            estimated_baud=est_baud,
            uncertainty_baud=parameter_result.symbol_rate.uncertainty,
            details={
                "method": parameter_result.symbol_rate.method,
                "estimator_confidence": float(parameter_result.symbol_rate.confidence),
            },
        )

        # Real SNR evidence from M8 (neutral NOT_EVALUATED state per project rule)
        cand.evidence.snr = create_snr_evidence(
            estimated_snr_db=est_snr,
            uncertainty_db=parameter_result.snr_db.uncertainty,
            status=EvidenceStatus.NOT_EVALUATED,
            details={
                "method": parameter_result.snr_db.method,
                "estimator_confidence": float(parameter_result.snr_db.confidence),
            },
        )

    return candidates
